### PR TITLE
core: Add / Improve French translation

### PR DESCRIPTION
**Pull request by PingoLeon**
Thanks for maintaining this project, I tweaked and added some translations that were uncorrect / missing.
Please note it may not be perfect, feel free to improve it.

Note : re-did the pull request so that there's no more than one commit for these small changes.

### CODE REVIEW

**Comment by Myzel394** [comment]
> Please note it may not be perfect, feel free to improve it.

Are you a native speaker of the French language? 

> Note : re-did the pull request so that there's no more than one commit for these small changes.

Okay no problem but it would also not be a problem to have more than one commit. More commits are actually better in most of the cases as they provide more granular control.

**Comment by PingoLeon** [comment]
> Are you a native speaker of the French language?

Yes I am. I said that because in French there's many ways to say the same things but with whole different words (e g : "Paramètres supplémentaires" = "Réglages Additionnels") and one translation may be more accurate than others following the context.

**Comment by PingoLeon** [comment]
Didn't know that deleting my copy of the repo would close this PR. 
Could you change the file with the content of https://github.com/Myzel394/NumberHub/pull/45/files (split view) please ?
Or should I re-open a PR ?

**Comment by Myzel394** [comment]
Please re-open it, this way you'll be authored correctly. Sorry, I wanted to merge it after it became green but forgot it

**Pull request closed without merging**
